import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "../store/StoreProvider";
import { PreviewBanner } from "@/components/cms/PreviewBanner";
import { DemoModalRoot } from "@/components/demo/DemoModalRoot";
import { CloudsProvider } from "@/components/ui/CloudsContext";
import { SmoothAnchors } from "@/components/ui/SmoothAnchors";
import { getGlobal } from "@/lib/cms/queries";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const global = await getGlobal().catch(() => null);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      {/* suppressHydrationWarning: browser extensions (e.g. ColorZilla) inject body attrs */}
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {/* We wrap the entire application in our Redux StoreProvider */}
        {/* It's important to put this here so all components can access Redux state */}
        <StoreProvider>
          <CloudsProvider value={{ edge: global?.cloudEdge, band: global?.cloudBand }}>
            <SmoothAnchors />
            <PreviewBanner />
            {children}
            <DemoModalRoot />
          </CloudsProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
